# Service definition for the admission webhook
apiVersion: v1
kind: Service
metadata:
  name: archivista
  namespace: archivista
spec:
  type: NodePort
  selector:
    app: archivista
  ports:
    - name: api
      port: 8082
      targetPort: 8082
